# defaults are setup for the platform engineering slack workspace
slack:
  report_channel: bot-test
  report_channel_id: C01KHKNJUKE

jira:
  project: SBOX

secrets:
  cftptl-intsvc:
    jira-username: JIRA_USERNAME
    jira-api-token: JIRA_API_TOKEN
    idam-slack-bot-token: SLACK_BOT_TOKEN
    idam-slack-app-token: SLACK_APP_TOKEN

service-refresh-time: 15